from enum import Enum #Enumerations are used to define a set of named values
from pydantic import BaseModel, Field
#BaseModel is the base class for all Pydantic models to define the structure of the data like for example, the fields and their types.
#Field is used to provide additional information about the fields in the model and which are required/mandatory.
#to give random values for the fields then we can use the following approach:
# by using the `default_factory` parameter in the Field function.
# we need to import randint from the random module, 
# The syntax is "from random import randint" works only in python 3.6+ and for onky random integer values.

#def random_weight():
#    return randint(1, 40)

class ShipmentStatus(str, Enum): #here Enum is used to create an enumeration. enumurate means to assign a name to each value in the enumeration.
    PENDING = "Pending"
    IN_TRANSIT = "In Transit"
    DELIVERED = "Delivered"
    DELAYED = "Delayed"

class Baseshipment(BaseModel):
    origin: str = Field(min_length=3, max_length=100)
    destination: str = Field(min_length=2, max_length=100)
    weight: float = Field(gt=0, le=40, description= "Weight of the shipment in kilograms") 
    # = Field(default_factory= randint(1, 40))
    #= Field(default_factory= random_weight)

class Readshipment(Baseshipment):
    shipment_status: ShipmentStatus  


class Createshipment(Baseshipment):
    pass

class Updateshipment(BaseModel):
    shipment_status: ShipmentStatus | None = None



#question: Let's make this even more concrete. Think about what happens after a shipment is created or updated. What kind of information would the system add to the shipment data before sending it back to the user? For instance, when you create a new shipment, the system might assign it a unique ID. Would that ID be part of the ShipmentCreate request, or would it be something the ShipmentRead response would include?

#What other fields might be generated by the system and thus only appear in ShipmentRead?
#answer: The system might generate a unique ID for each shipment, which would only appear in the ShipmentRead response. Other fields that might be generated by the system include timestamps for when the shipment was created or last updated, and possibly a tracking number.
   